# Generated by Django 3.1.1 on 2025-03-14 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_resdownet_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='resdownet_token',
        ),
    ]
