# Generated by Django 3.1.1 on 2025-03-13 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_project_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0013_auto_20201023_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.CreateModel(
            name='CardMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='boards.item')),
                ('moved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_movements', to=settings.AUTH_USER_MODEL)),
                ('to_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_movements', to='boards.list')),
            ],
        ),
    ]
