# Generated by Django 4.2.20 on 2025-03-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0014_auto_20250313_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
